
- name: base
  doc: Assemble application configuration including user authorization details
  blocks:
    nav:
      - name: main-nav
        handler: baseNavHandler
        default: true
        doc: principle navigation for site
      - name: settings-nav
        handler: baseNavHandler
        doc: navigation while in settings view

    wrapper:
      - name: landing
        default: true
        doc: General admin search area
        path: /admin
        blocks:
          landing-results:
            - name: user-search-results
              path: /admin/user-search

            - name: role-search-results
              path: /admin/role-search

      - name: history
        doc: Allow history log to be searched
        path: /admin/history

      - name: account
        doc: Administer admin user account
        path: /admin/account

      - name: user
        doc: Display user information
        path: /admin/user/{user}/
        blocks:
          user-content:
            - default: true
              name: user-roles-list
              path: /admin/users/{user}/roles

            - name: user-roles-edit
              path: /admin/users/{user}/edit

            - name: user-assign-roles
              path: /admin/users/{user}/assign

            - fragment: true
              name: user-find-roles-results
              path: /admin/users/{user}/find-role-roles

            - fragment: true
              name: user-assign-role-complete
              path: /admin/users/{user}/assign-roles-complete

            - fragment: true
              name: user-revoke-role-complete
              path: /admin/users/{user}/revoke-roles-complete

      - name: role
        path: /admin/roles/{role}/
        blocks:
          role-content:
            - default: true
              name: role-users-list
              path: /admin/roles/{role}/users

            - name: role-users-edit
              path: /admin/roles/{role}/edit

            - name: role-assign-users
              path: /admin/roles/{role}/assign

            - fragment: true
              name: role-assign-results-roles
              path: /admin/roles/{role}/find-user-roles-results

            - fragment: true
              name: role-assign-results-users
              path: /admin/roles/{role}/find-users-results

            - fragment: true
              name: role-assign-role-complete
              path: /admin/roles/{role}/assign-role-users-complete

            - fragment: true
              name: role-revoke-users-complete
              path: /admin/roles/{role}/assign-users-complete
