
- name: base
  template: templates/base.templ.html
  blocks:
    wrapper:
      - name: landing
        default: true
        path: /admin
        template: templates/landing.templ.html
        blocks:
          landing-results:
            - name: user-search-results
              path: /admin/user-search
              template: templates/user-search-results.templ.html

            - name: role-search-results
              path: /admin/role-search
              template: templates/role-search-results.templ.html

      - name: history
        path: /admin/history
        template: templates/history.templ.html

      - name: account
        path: /admin/account
        template: templates/account.templ.html

      - name: user
        path: /admin/user/{user}/
        template: templates/user.templ.html
        blocks:
          user-content:
            - default: true
              name: user-roles-list
              path: /admin/users/{user}/roles
              template: templates/user-roles-list.templ.html
            - name: user-roles-edit
              path: /admin/users/{user}/edit
              template: templates/user-roles-edit.templ.html
            - name: user-assign-roles
              path: /admin/users/{user}/assign
              template: templates/user-assign-roles.templ.html

            - fragment: true
              name: user-find-roles-results
              path: /admin/users/{user}/find-role-roles
              template: templates/fragments/user-find-roles-results.html
            - fragment: true
              name: user-assign-role-complete
              path: /admin/users/{user}/assign-roles-complete
              template: templates/fragments/user-assign-role-complete.templ.html
            - fragment: true
              name: user-revoke-role-complete
              path: /admin/users/{user}/revoke-roles-complete
              template: templates/fragments/user-revoke-role-complete.templ.html

      - name: role
        path: /admin/roles/{role}/
        template: templates/role.templ.html
        blocks:
          role-content:
            - default: true
              name: role-users-list
              path: /admin/roles/{role}/users
              template: templates/role-users-list.templ.html
            - name: role-users-edit
              path: /admin/roles/{role}/edit
              template: templates/role-users-edit.templ.html
            - name: role-assign-users
              path: /admin/roles/{role}/assign
              template: templates/role-assign-users.templ.html

            - fragment: true
              name: role-assign-results-roles
              path: /admin/roles/{role}/find-user-roles-results
              template: templates/fragments/role-assign-results-roles.html
            - fragment: true
              name: role-assign-results-users
              path: /admin/roles/{role}/find-users-results
              template: templates/fragments/role-assign-results-users.html
            - fragment: true
              name: role-assign-role-complete
              path: /admin/roles/{role}/assign-role-users-complete
              template: templates/fragments/role-assign-role-complete.templ.html
            - fragment: true
              name: role-revoke-users-complete
              path: /admin/roles/{role}/assign-users-complete
              template: templates/fragments/role-revoke-users-complete.templ.html

      - name: message
        template: templates/message.templ.htm


  flash:
