// Code generated by go generate; DO NOT EDIT.

// This file was created by github.com/rur/ttgen/cmd/ttroutes
// Map file: ./routemap.toml
// Template file: ./routes.go.templ

package ticket

import (
	"net/http"

	"github.com/rur/treetop"
)

func Routes(m *http.ServeMux, exec treetop.ViewExecutor) {

	baseView := treetop.NewView(
		"local://base.html",
		treetop.Delegate("content"),
	)

	// content
	ticketFormContent := baseView.NewDefaultSubView(
		"content",
		"examples/ticket/templates/content/ticketFormContent.html.tmpl",
		ticketHandler,
	)

	// content -> form
	newHelpdeskTicket := ticketFormContent.NewSubView(
		"form",
		"examples/ticket/templates/content/form/newHelpdeskTicket.html.tmpl",
		newHelpdeskTicketHandler,
	)

	// content -> form -> reported-by
	helpdeskReportedBy := newHelpdeskTicket.NewDefaultSubView(
		"reported-by",
		"examples/ticket/templates/content/form/reportedBy/helpdeskReportedBy.html.tmpl",
		helpdeskReportedByHandler,
	)

	// content -> form -> reported-by -> find-reported-by
	findHelpdeskReportedBy := helpdeskReportedBy.NewSubView(
		"find-reported-by",
		"examples/ticket/templates/content/form/reportedBy/findReportedBy/findHelpdeskReportedBy.html.tmpl",
		findTeamMemberHandler,
	)
	newSoftwareTicket := ticketFormContent.NewSubView(
		"form",
		"examples/ticket/templates/content/form/newSoftwareTicket.html.tmpl",
		newSoftwareTicketHandler,
	)
	newSystemsTicket := ticketFormContent.NewSubView(
		"form",
		"examples/ticket/templates/content/form/newSystemsTicket.html.tmpl",
		newSystemsTicketHandler,
	)

	// nav
	_ = baseView.NewDefaultSubView(
		"nav",
		"local://nav.html",
		treetop.Noop,
	)

	m.Handle("/ticket/helpdesk/find-reported-by",
		exec.NewViewHandler(findHelpdeskReportedBy).FragmentOnly())
	m.Handle("/ticket/helpdesk/update-reported-by",
		exec.NewViewHandler(helpdeskReportedBy).FragmentOnly())
	m.Handle("/ticket/helpdesk/new",
		exec.NewViewHandler(newHelpdeskTicket))
	m.Handle("/ticket/software/new",
		exec.NewViewHandler(newSoftwareTicket))
	m.Handle("/ticket/systems/new",
		exec.NewViewHandler(newSystemsTicket))
	m.Handle("/ticket",
		exec.NewViewHandler(ticketFormContent))

}
