namespace = "github.com/treetop/demo"
page = "ticket"

[views]
  [views.base]
    name = "base"
    handler = "treetop.Delegate(\"content\")"
    template = "local://base.html"
    doc = "HTML template for demo demo site"
    uri = "/ticket"
    [views.base.blocks]

      [[views.base.blocks.content]]
        name = "issue-preview"
        handler = "handlers.IssuePreviewHandler"
        template = "demo/ticket/templates/content/issuePreview.html.tmpl"
        doc = "Content wrapper around preview for different ticket type"
        [views.base.blocks.content.blocks]

          [[views.base.blocks.content.blocks.notes]]
            name = "preview-notes"
            default = true
            handler = "treetop.Noop"
            template = "demo/ticket/templates/content/notes.html.tmpl"

          [[views.base.blocks.content.blocks.preview]]
            name = "preview-software-ticket"
            path = "/ticket/software/preview"
            handler = "handlers.PreviewSoftwareTicketHandler"
            template = "demo/ticket/templates/content/previewSoftwareTicket.html.tmpl"
            method = "GET"
            doc = "Show preview of software ticket, no database so take details form query params"

          [[views.base.blocks.content.blocks.preview]]
            name = "preview-helpdesk-ticket"
            path = "/ticket/helpdesk/preview"
            handler = "handlers.PreviewHelpdeskTicketHandler"
            template = "demo/ticket/templates/content/previewHelpdeskTicket.html.tmpl"
            method = "GET"
            doc = "Show preview of help desk ticket, no database so take details form query params"

          [[views.base.blocks.content.blocks.preview]]
            name = "preview-systems-ticket"
            path = "/ticket/systems/preview"
            handler = "handlers.PreviewSystemsTicketHandler"
            template = "demo/ticket/templates/content/previewSystemsTicket.html.tmpl"
            method = "GET"
            doc = "Show preview of systems ticket, no database so take details form query params"

      [[views.base.blocks.content]]
        name = "ticket-form-content"
        default = true
        path = "/ticket"
        handler = "handlers.TicketHandler"
        template = "demo/ticket/templates/content/ticketFormContent.html.tmpl"
        method = "GET"
        doc = "Landing page for ticket wizard"
        [views.base.blocks.content.blocks]

          [[views.base.blocks.content.blocks.form]]
            name = "new-helpdesk-ticket"
            path = "/ticket/helpdesk/new"
            handler = "handlers.NewHelpdeskTicketHandler"
            template = "demo/ticket/templates/content/form/newHelpdeskTicket.html.tmpl"
            method = "GET"
            doc = "Form designed for creating helpdesk tickets"
            [views.base.blocks.content.blocks.form.blocks]

              [[views.base.blocks.content.blocks.form.blocks.attachment-list]]
                name = "helpdesk-attachment-file-list"
                fragment = true
                default = true
                handler = "handlers.AttachmentFileListHandler"
                template = "demo/ticket/templates/content/form/attachmentList/uploadedFiles.html.tmpl"
                doc = "Default helpdesk attachment file list template handler, parse file info from query string"

              [[views.base.blocks.content.blocks.form.blocks.attachment-list]]
                name = "uploaded-helpdesk-files"
                fragment = true
                path = "/ticket/helpdesk/upload-attachment"
                handler = "handlers.UploadedFilesHandler"
                template = "demo/ticket/templates/content/form/attachmentList/uploadedFiles.html.tmpl"
                method = "POST"
                doc = "Load a list of uploaded files, save to storage and return metadata to the form"

              [[views.base.blocks.content.blocks.form.blocks.form-message]]
                name = "submit-help-desk-ticket"
                fragment = true
                path = "/ticket/helpdesk/submit"
                handler = "handlers.SubmitHelpDeskTicketHandler"
                template = "demo/ticket/templates/content/form/formMessage/submitHelpDeskTicket.html.tmpl"
                method = "POST"
                doc = "process creation of a new help desk ticket"

              [[views.base.blocks.content.blocks.form.blocks.notes]]
                name = "new-helpdesk-notes"
                default = true
                handler = "treetop.Noop"
                template = "demo/ticket/templates/content/notes.html.tmpl"
                doc = "Show this when helpdesk form is loaded"

              [[views.base.blocks.content.blocks.form.blocks.reported-by]]
                name = "helpdesk-reported-by"
                fragment = true
                default = true
                path = "/ticket/helpdesk/update-reported-by"
                handler = "handlers.HelpdeskReportedByHandler"
                template = "demo/ticket/templates/content/form/reportedBy/helpdeskReportedBy.html.tmpl"
                method = "GET"
                doc = "Options for notifying help desk of who reported the issue"
                [views.base.blocks.content.blocks.form.blocks.reported-by.blocks]

                  [[views.base.blocks.content.blocks.form.blocks.reported-by.blocks.find-user]]
                    name = "find-helpdesk-reported-by"
                    fragment = true
                    default = true
                    path = "/ticket/helpdesk/find-reported-by"
                    handler = "handlers.FindReportedByUserHandler"
                    template = "demo/ticket/templates/content/form/reportedBy/findReportedByUser.html.tmpl"
                    method = "GET"
                    doc = "query string to find a user to select"

          [[views.base.blocks.content.blocks.form]]
            name = "new-software-ticket"
            path = "/ticket/software/new"
            handler = "handlers.NewSoftwareTicketHandler"
            template = "demo/ticket/templates/content/form/newSoftwareTicket.html.tmpl"
            method = "GET"
            doc = "Form designed for creating software tickets"
            [views.base.blocks.content.blocks.form.blocks]

              [[views.base.blocks.content.blocks.form.blocks.assignee]]
                name = "view-software-assignee"
                fragment = true
                default = true
                path = "/ticket/software/update-assignee"
                handler = "handlers.SoftwareAssigneeHandler"
                template = "demo/ticket/templates/content/form/assignee/assignee-input.html.tmpl"
                doc = "Select multiple users as assignees"
                [views.base.blocks.content.blocks.form.blocks.assignee.blocks]

                  [[views.base.blocks.content.blocks.form.blocks.assignee.blocks.find-user]]
                    name = "find-software-assignee"
                    fragment = true
                    default = true
                    path = "/ticket/software/find-assignee"
                    handler = "handlers.SoftwareFindAssigneeHandler"
                    template = "demo/ticket/templates/content/form/assignee/find-assignee.html.tmpl"
                    method = "GET"
                    doc = "query string to find a user to select"

              [[views.base.blocks.content.blocks.form.blocks.attachment-list]]
                name = "software-attachment-file-list"
                fragment = true
                default = true
                handler = "handlers.AttachmentFileListHandler"
                template = "demo/ticket/templates/content/form/attachmentList/uploadedFiles.html.tmpl"
                doc = "Default software attachment file list template handler, parse file info from query string"

              [[views.base.blocks.content.blocks.form.blocks.attachment-list]]
                name = "uploaded-software-files"
                fragment = true
                path = "/ticket/software/upload-attachment"
                handler = "handlers.UploadedFilesHandler"
                template = "demo/ticket/templates/content/form/attachmentList/uploadedFiles.html.tmpl"
                method = "POST"
                doc = "Load a list of uploaded files, save to storage and return metadata to the form"

              [[views.base.blocks.content.blocks.form.blocks.form-message]]
                name = "submit-software-ticket"
                fragment = true
                path = "/ticket/software/submit"
                handler = "handlers.SubmitSoftwareTicketHandler"
                template = "demo/ticket/templates/content/form/formMessage/submitSoftwareTicket.html.tmpl"
                method = "POST"
                doc = "process creation of a new software ticket"

              [[views.base.blocks.content.blocks.form.blocks.notes]]
                name = "view-software-notes"
                default = true
                handler = "treetop.Noop"
                template = "demo/ticket/templates/content/notes.html.tmpl"
                doc = "Show this when software form is loaded"

          [[views.base.blocks.content.blocks.form]]
            name = "new-systems-ticket"
            path = "/ticket/systems/new"
            handler = "handlers.NewSystemsTicketHandler"
            template = "demo/ticket/templates/content/form/newSystemsTicket.html.tmpl"
            method = "GET"
            doc = "Form designed for creating systems tickets"
            [views.base.blocks.content.blocks.form.blocks]

              [[views.base.blocks.content.blocks.form.blocks.attachment-list]]
                name = "systems-attachment-file-list"
                fragment = true
                default = true
                handler = "handlers.AttachmentFileListHandler"
                template = "demo/ticket/templates/content/form/attachmentList/uploadedFiles.html.tmpl"
                doc = "Default systems attachment file list template handler, parse file info from query string"

              [[views.base.blocks.content.blocks.form.blocks.attachment-list]]
                name = "uploaded-systems-files"
                fragment = true
                path = "/ticket/systems/upload-attachment"
                handler = "handlers.UploadedFilesHandler"
                template = "demo/ticket/templates/content/form/attachmentList/uploadedFiles.html.tmpl"
                method = "POST"
                doc = "Load a list of uploaded files, save to storage and return metadata to the form"

              [[views.base.blocks.content.blocks.form.blocks.component-tags]]
                name = "systems-component-tags-input-group"
                fragment = true
                default = true
                path = "/ticket/systems/update-tags"
                handler = "handlers.SystemsComponentTagsInputGroupHandler"
                template = "demo/ticket/templates/content/form/componentTags/systemsComponentTagsInputGroup.html.tmpl"
                doc = "Load form input group for the component tags selector"
                [views.base.blocks.content.blocks.form.blocks.component-tags.blocks]

                  [[views.base.blocks.content.blocks.form.blocks.component-tags.blocks.tag-search]]
                    name = "systems-component-tag-search"
                    fragment = true
                    path = "/ticket/systems/find-tag"
                    handler = "handlers.SystemsComponentTagSearchHandler"
                    template = "demo/ticket/templates/content/form/componentTags/systemsComponentTagSearch.html.tmpl"
                    doc = "fuzzy match query to available systems component tags"

              [[views.base.blocks.content.blocks.form.blocks.form-message]]
                name = "submit-systems-ticket"
                fragment = true
                path = "/ticket/systems/submit"
                handler = "handlers.SubmitSystemsTicketHandler"
                template = "demo/ticket/templates/content/form/formMessage/submitSystemsTicket.html.tmpl"
                method = "POST"
                doc = "process creation of a new systems ticket"

              [[views.base.blocks.content.blocks.form.blocks.notes]]
                name = "view-systems-notes"
                default = true
                handler = "treetop.Noop"
                template = "demo/ticket/templates/content/notes.html.tmpl"
                doc = "Show this when systems form is loaded"

      [[views.base.blocks.nav]]
        name = "demo-nav"
        default = true
        handler = "treetop.Noop"
        template = "local://nav.html"
        doc = "Navigate between the different demo apps"
